FROM golang:1.17-alpine as builder

RUN set -ex; \
    apk update; \
    apk add --no-cache \
     ca-certificates curl build-base make bash ruby

ENV  GOPATH=$HOME/go
ENV  PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Install godog
RUN go install github.com/cucumber/godog/cmd/godog@v0.12.0
# Gosec
RUN curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

# Pact
RUN curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | sh -s -- -b $(go env GOPATH)
ENV PATH=$PATH:$GOPATH/pact/bin
RUN go install github.com/pact-foundation/pact-go@v1

WORKDIR /opt/app

# Fetch dependencies
COPY go.mod go.sum ./
RUN go mod download

# Build
COPY . ./
CMD go run ./form3-client.go
# CMD sh testing.sh

# CMD GOOS=linux CGO_ENABLED=0 go test ./...  -coverprofile=coverage.out

# # Build Go Binary
# RUN set -ex; \
#     CGO_ENABLED=0 GOOS=linux go build ./*.go;

# # Create final image
# FROM alpine:latest

# # Install Root Ceritifcates
# RUN set -ex; \
#     apk update; \
#     apk add --no-cache \
#      ca-certificates

# WORKDIR /opt/

# COPY --from=builder /go/src/github.com/gaikwadamolraj/form3/form3-client .

# CMD /opt/form3-client