name: Go

on:
  push:
    branches: [ mydevops ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install dependencies
      run: |
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
        curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
        curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | bash
        export PATH=$PATH:$PWD/pact/bin
        go install github.com/pact-foundation/pact-go@v1
        go mod vendor

    - name: Test
      run: go test ./form3/... -coverprofile=coverage.out
    
    - name: Security Scan
      run: gosec -exclude-dir=vendor ./...

    - name: Pact - Contract test
      run: go test -v ./contract-testing/pact_test.go